# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty
cache: packages

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
